# -*- coding: utf-8 -*-
"""Introduçao a Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zlpyPYzI4aNKShtgj4cJwpfLZWYbvuLV

# Analisando algumas notas
"""

import pandas as pd
notes = pd.read_csv("ratings.csv")
notes.head()

"""notes.shape"""

notes.columns = ["usuarioId", "filmeId", "nota", "momento"]
notes.head()

notes["nota"].unique()

notes["nota"].value_counts()

notes["nota"].mean()

notes.head()

print("Media",notes.nota.mean())
print("Mediana",notes.nota.median())

notes.nota.plot(kind="hist")

notes.nota.describe()

import seaborn as sns

sns.boxplot(notes.nota)

"""# Movie"""

import pandas as pd

filmes = pd.read_csv("movies.csv")
filmes.head

filmes.columns = ["filmeId", "nome", "generos"]
notas.columns = ["usuarioId", "filmeId", "nota", "momento"]

notas = pd.read_csv("ratings.csv")
notas.head

"""#Analisando algumas notas especificas por filme"""

notas.query("filmeId==1").nota.mean()

filmes.query("filmeId==2683")

medias_por_filme = notas.groupby("filmeId").mean().nota
medias_por_filme.head

medias_por_filme.plot(kind="hist")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=[5,8])
sns.boxplot(y=medias_por_filme)

medias_por_filme.describe()

sns.distplot(medias_por_filme)

import matplotlib.pyplot as plt
plt.hist(medias_por_filme)
plt.title("Histograma das medias dos filmes")

notas.nota.plot(kind="hist")

notas.nota.describe()

plt.figure(figsize=[5,8])
sns.boxplot(y=notas.nota)

notas.query("filmeId==1").nota.mean()

notas.query("filmeId==2").nota.mean()

notas.groupby("filmeId").mean().nota