# -*- coding: utf-8 -*-
"""Introduçao a Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zlpyPYzI4aNKShtgj4cJwpfLZWYbvuLV

# Analyzing movies ratings
"""

import pandas as pd
notes = pd.read_csv("ratings.csv")
notes.head()

"""notes.shape"""

notes.columns = ["usuarioId", "filmeId", "nota", "momento"]
notes.head()

notes["nota"].unique()

notes["nota"].value_counts()

notes["nota"].mean()

notes.head()

print("Media",notes.nota.mean())
print("Mediana",notes.nota.median())

notes.nota.plot(kind="hist")

notes.nota.describe()

import seaborn as sns

sns.boxplot(notes.nota)

"""# Movie"""

import pandas as pd

filmes = pd.read_csv("movies.csv")
filmes.head()

notas = pd.read_csv("ratings.csv")

filmes.columns = ["filmeId", "nome", "generos"]
notas.columns = ["usuarioId", "filmeId", "nota", "momento"]

notas.head()

"""# Analysing some specific ratings by movie"""

notas.query("filmeId==1").nota.mean()

filmes.query("filmeId==2683")

medias_por_filme = notas.groupby("filmeId").mean().nota
medias_por_filme.head

medias_por_filme.plot(kind="hist")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=[5,8])
sns.boxplot(y=medias_por_filme)

medias_por_filme.describe()

sns.distplot(medias_por_filme)

import matplotlib.pyplot as plt
plt.hist(medias_por_filme)
plt.title("Histograma das medias dos filmes")

notas.nota.plot(kind="hist")

notas.nota.describe()

plt.figure(figsize=[5,8])
sns.boxplot(y=notas.nota)

notas.query("filmeId==1").nota.mean()

notas.query("filmeId==2").nota.mean()

notas.groupby("filmeId").mean().nota

"""#The Movie Database (TMDB)"""

import pandas as pd

tmdb = pd.read_csv("tmdb_5000_movies.csv")
tmdb.head()

tmdb.original_language.unique()

tmdb.vote_average.unique()

"""#TMDB - Comparing movies"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ratings = pd.read_csv("ratings.csv")

ratings.head()

rating_toy_story = ratings.query("movieId==1")
rating_jumanji = ratings.query("movieId==2")

print(len(rating_toy_story), len(rating_jumanji))

print ("Mean rating of Toy Story %.2f" % rating_toy_story.rating.mean())
print ("Mean rating of Jumanji %.2f" % rating_jumanji.rating.mean())

print ("Standard deviation of Toy Story %.2f" % rating_toy_story.rating.std())
print ("Standard deviation of Jumanji %.2f" % rating_jumanji.rating.mean())

print ("Median rating of Toy Story %.2f" % np.median(rating_toy_story.rating))
print ("Median rating of Jumanji %.2f" % np.median(rating_jumanji.rating))

sns.boxplot(x = "movieId", y = "rating", data = ratings.query("movieId in [1,2]"))

filme1 = np.append(np.array([2.5]*10), np.array([3.5]*10))
filme2 = np.append(np.array([1.0]*10), np.array([5.0]*10))

print ("Means", filme1.mean(), filme2.mean())
print ("Standard deviation", filme1.std(), filme2.std())
print ("Median", np.median(filme1), np.median(filme2))

plt.hist(filme1)
plt.hist(filme2)

plt.boxplot([filme1, filme2])

